-- SORTING CUSTOMERS WITH CANCELLED DELIVERIES--
SELECT ORDERID, C.FIRSTNAME AS CUSTOMERNAME, ORDERDATE, ITEM, QUANTITY, DELIVERYSTATUS
FROM ORDERSS O
LEFT JOIN CUSTOMERS C USING (CUSTOMERID)
WHERE DELIVERYSTATUS = 'CANCELLED';

-- SORTING CUSTOMERS WHO ORDERED FOR 1000LITERS AND ABOVE AGO PRODUCT --
SELECT ORDERID, C.FIRSTNAME AS CUSTOMERNAME, ORDERDATE, ITEM, QUANTITY, DELIVERYSTATUS
FROM ORDERSS O
LEFT JOIN CUSTOMERS C USING (CUSTOMERID)
WHERE ITEM = 'AGO' AND QUANTITY >=1000;

-- IDENTIFYING CUSTOMERS WHOSE ORDERS HAVE BEEN SHIPPED FROM INVENTORY --
SELECT ORDERID, C.FIRSTNAME AS CUSTOMERNAME, ITEM, QUANTITY, SHIPSTATUS, E.FIRSTNAME AS SALESREP
FROM ORDERSS O
LEFT JOIN CUSTOMERS C USING (CUSTOMERID)
JOIN EMPLOYEES E ON O.SALESREP = E.EMPLOYEEID
WHERE SHIPSTATUS = 'SHIPPED'
ORDER BY CUSTOMERNAME ASC;

-- IDENTIFYING TOTAL QUANTITY DELIVERED BY EACH TRANSPORTER --
SELECT T.NAME AS TRANSPORTER, SUM(O.QUANTITY)
FROM ORDERSS O
LEFT JOIN CUSTOMERS C USING (CUSTOMERID)
JOIN EMPLOYEES E ON O.SALESREP = E.EMPLOYEEID
JOIN TRANSPORTERS T ON O.TRANSPORTER = T.TRANSPORTERID
GROUP BY TRANSPORTER;

-- IDENTIFYING HOW MUCH DELIVERIES WERE DONE FOR EACH REGION --
SELECT DESTINATIONS, SUM(O.QUANTITY)
FROM ORDERSS O
LEFT JOIN CUSTOMERS C USING (CUSTOMERID)
JOIN EMPLOYEES E ON O.SALESREP = E.EMPLOYEEID
JOIN TRANSPORTERS T ON O.TRANSPORTER = T.TRANSPORTERID
GROUP BY DESTINATIONS;

-- IDENTIFYING WHICH EMPLOYEES MADE THE LARGEST SALE QUANTITY --
SELECT SALESREP, E.FIRSTNAME AS EMPLOYEENAME, SUM(QUANTITY) AS QTYSOLD
FROM ORDERSS O
LEFT JOIN CUSTOMERS C USING (CUSTOMERID)
JOIN EMPLOYEES E ON O.SALESREP = E.EMPLOYEEID
JOIN TRANSPORTERS T ON O.TRANSPORTER = T.TRANSPORTERID
GROUP BY SALESREP
ORDER BY QTYSOLD DESC;

-- GETTING FULL DETAILS OF EACH ORDER --
SELECT ORDERID, ORDERDATE, C.FIRSTNAME AS CUSTOMER, ITEM, QUANTITY, O.DELIVERYSTATUS, E.FIRSTNAME AS SALESREP, D.DEPARTMENTNAME, T.NAME AS TRANSPORTER 
FROM ORDERSS O
JOIN CUSTOMERS C USING (CUSTOMERID)
JOIN EMPLOYEES E ON O.SALESREP = E.EMPLOYEEID
JOIN DEPARTMENTS D ON D.DEPARTMENTCODE = E.DEPARTMENTID
JOIN TRANSPORTERS T ON O.TRANSPORTER = T.TRANSPORTERID
ORDER BY CUSTOMER ASC;